services:
  rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: rtmp
    restart: unless-stopped
    environment:
      RECORD_DURATION: ${RECORD_DURATION:-300s}
    ports:
      - "1935:1935" # RTMP ingest
      - "80:80" # simple http status + local /recordings browsing (optional)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - recordings_data:/recordings
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  publisher:
    image: amazon/aws-cli:latest
    container_name: publisher
    restart: unless-stopped
    environment:
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX}
      PUBLIC_ACL: ${PUBLIC_ACL}
      SYNC_INTERVAL_SECONDS: ${SYNC_INTERVAL_SECONDS}
      MP4_MAXAGE: ${MP4_MAXAGE}
      RECORDINGS_DIR: ${RECORDINGS_DIR}
    volumes:
      - recordings_data:/recordings:ro
      - ./publisher/publish.sh:/publish.sh:ro
    entrypoint: ["/bin/sh", "/publish.sh"]

volumes:
  recordings_data:
