services:
  ngx-rtmp:
    container_name: ngx-rtmp
    image: alfg/nginx-rtmp:latest
    platform: linux/arm64 # remove this line if you run x86_64
    restart: unless-stopped
    ports:
      - "1935:1935" # RTMP ingest
      - "80:80" # HTTP for HLS/debug
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./hls:/hls
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://127.0.0.1/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
