services:
  rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: rtmp
    restart: unless-stopped
    environment:
      RECORD_DURATION: ${RECORD_DURATION:-300s}
    ports:
      - "1935:1935"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - recordings_data:/recordings
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  remuxer:
    image: jrottenberg/ffmpeg:4.4-alpine
    container_name: remuxer
    restart: unless-stopped
    environment:
      QUIET_SECONDS: ${QUIET_SECONDS:-60}
      FLV_MAX_AGE_SECONDS: ${FLV_MAX_AGE_SECONDS:-0}
    volumes:
      - recordings_data:/recordings
      - ./remuxer/remux.sh:/remux.sh:ro
    entrypoint: ["/bin/sh", "/remux.sh"]

  publisher:
    image: amazon/aws-cli:latest
    container_name: publisher
    restart: unless-stopped
    environment:
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX}
      PUBLIC_ACL: ${PUBLIC_ACL}
      SYNC_INTERVAL_SECONDS: ${SYNC_INTERVAL_SECONDS:-10}
      RECORDINGS_DIR: /recordings/mp4
    volumes:
      - recordings_data:/recordings:ro
      - ./publisher/publish.sh:/publish.sh:ro
    entrypoint: ["/bin/sh", "/publish.sh"]

volumes:
  recordings_data:
