services:
  rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: rtmp
    restart: unless-stopped
    ports:
      - "1935:1935" # RTMP ingest
      - "80:80" # simple http status + local /hls browsing (optional)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - hls_data:/hls
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  publisher:
    image: amazon/aws-cli:latest
    container_name: publisher
    restart: unless-stopped
    environment:
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX}
      PUBLIC_ACL: ${PUBLIC_ACL}
      SYNC_INTERVAL_SECONDS: ${SYNC_INTERVAL_SECONDS}
      PLAYLIST_MAXAGE: ${PLAYLIST_MAXAGE}
      SEGMENT_MAXAGE: ${SEGMENT_MAXAGE}
      HLS_DIR: ${HLS_DIR}
    volumes:
      - hls_data:/hls:ro
      - ./publisher/publish.sh:/publish.sh:ro
    entrypoint: ["/bin/sh", "/publish.sh"]

volumes:
  hls_data:
